package com.smarterp.pos

import java.text.NumberFormat
import java.util.Locale
import woyou.aidlservice.jiuiv5.IWoyouService

/**
 * ReceiptPrinter — formats and sends receipt data to the SUNMI built-in
 * printer via the AIDL service obtained from SunmiPrinterManager.
 *
 * Layout mirrors the detailed HTML receipt generated by the TypeScript
 * `generateDetailedReceiptHTML` function in `samplepos.client/src/lib/print.ts`
 * so the printed output is visually consistent between platforms.
 *
 * This object is only ever called from PrintBridge (i.e. when the device IS
 * a SUNMI).  The ESC/POS and browser-print paths are completely unaffected.
 */
object ReceiptPrinter {

    /**
     * Hard test — call this from ADB or a debug button to bypass receipt
     * formatting entirely.  If this prints → formatting is the issue.
     * If this does NOT print → the service is still not bound.
     *
     *   Usage (from PrintBridge for testing):
     *     ReceiptPrinter.hardTest()
     */
    fun hardTest() {
        val p = SunmiPrinterManager.get() ?: run {
            android.util.Log.e("SUNMI_TEST", "hardTest: printer not connected")
            return
        }
        try {
            p.printText("SUNMI HARD TEST\n", null)
            p.lineWrap(3, null)
            android.util.Log.e("SUNMI_TEST", "hardTest: sent to printer")
        } catch (e: Exception) {
            android.util.Log.e("SUNMI_TEST", "hardTest error: ${e.message}", e)
        }
    }

    fun printReceipt(data: ReceiptData) {
        val p = SunmiPrinterManager.get() ?: run {
            android.util.Log.e("SUNMI_TEST", "printReceipt: printer not connected — skipping")
            return
        }

        try {
            // ── Header ──────────────────────────────────────────────────────────────
            p.setAlignment(1, null) // centre
            if (!data.companyName.isNullOrBlank()) {
                p.setFontSize(28f, null)
                p.printText("${data.companyName}\n", null)
            }
            if (!data.companyAddress.isNullOrBlank()) {
                p.setFontSize(24f, null)
                p.printText("${data.companyAddress}\n", null)
            }
            if (!data.companyPhone.isNullOrBlank()) {
                p.printText("Tel: ${data.companyPhone}\n", null)
            }
            p.lineWrap(1, null)

            // ── Sale metadata ────────────────────────────────────────────────────────
            p.setAlignment(0, null) // left
            p.setFontSize(24f, null)
            p.printText("Receipt: ${data.saleNumber}\n", null)
            p.printText("Date:    ${data.saleDate}\n", null)
            if (!data.cashierName.isNullOrBlank()) {
                p.printText("Cashier: ${data.cashierName}\n", null)
            }
            if (!data.customerName.isNullOrBlank()) {
                p.printText("Customer: ${data.customerName}\n", null)
            }
            p.printText("--------------------------------\n", null)

            // ── Line items ───────────────────────────────────────────────────────────
            data.items?.forEach { item ->
                val label = if (!item.uom.isNullOrBlank()) "${item.name} (${item.uom})" else item.name
                // Name row
                p.printText("$label\n", null)
                // Qty × price = subtotal row (right-aligned amounts via columns)
                val qtyPrice = "  ${formatQty(item.quantity)} x ${fmt(item.unitPrice)}"
                val sub      = fmt(item.subtotal)
                p.printColumnsText(
                    arrayOf(qtyPrice, sub),
                    intArrayOf(24, 8),
                    intArrayOf(0, 2),
                    null
                )
                if ((item.discountAmount ?: 0.0) > 0.0) {
                    p.printText("  Discount: -${fmt(item.discountAmount!!)}\n", null)
                }
            }
            p.printText("--------------------------------\n", null)

            // ── Totals ───────────────────────────────────────────────────────────────
            if ((data.subtotal ?: 0.0) > 0.0 && data.subtotal != data.totalAmount) {
                printLabelValue(p, "Subtotal", fmt(data.subtotal!!))
            }
            if ((data.discountAmount ?: 0.0) > 0.0) {
                printLabelValue(p, "Discount", "-${fmt(data.discountAmount!!)}")
            }
            if ((data.taxAmount ?: 0.0) > 0.0) {
                printLabelValue(p, "Tax", fmt(data.taxAmount!!))
            }
            p.setFontSize(28f, null)
            printLabelValue(p, "TOTAL", fmt(data.totalAmount))
            p.setFontSize(24f, null)

            // ── Payment ──────────────────────────────────────────────────────────────
            p.printText("--------------------------------\n", null)
            if (!data.payments.isNullOrEmpty()) {
                data.payments.forEach { pay ->
                    printLabelValue(p, pay.method, fmt(pay.amount))
                }
            } else if (!data.paymentMethod.isNullOrBlank()) {
                printLabelValue(p, data.paymentMethod, fmt(data.amountPaid ?: data.totalAmount))
            }
            val change = data.changeGiven ?: data.changeAmount ?: 0.0
            if (change > 0.0) {
                printLabelValue(p, "Change", fmt(change))
            }

            // ── Footer ───────────────────────────────────────────────────────────────
            p.lineWrap(1, null)
            p.setAlignment(1, null)
            if (!data.customReceiptNote.isNullOrBlank()) {
                p.printText("${data.customReceiptNote}\n", null)
            } else {
                p.printText("Thank you for your business!\n", null)
            }
            p.lineWrap(3, null)

        } catch (e: Exception) {
            android.util.Log.e("ReceiptPrinter", "printReceipt error: ${e.message}", e)
        }
    }

    // ── Helpers ──────────────────────────────────────────────────────────────────

    private fun printLabelValue(p: IWoyouService, label: String, value: String) {
        p.printColumnsText(
            arrayOf(label, value),
            intArrayOf(24, 8),
            intArrayOf(0, 2),
            null
        )
    }

    private fun fmt(amount: Double): String {
        return NumberFormat.getNumberInstance(Locale.getDefault()).apply {
            minimumFractionDigits = 0
            maximumFractionDigits = 0
        }.format(amount)
    }

    private fun formatQty(qty: Double): String =
        if (qty == qty.toLong().toDouble()) qty.toLong().toString() else qty.toString()
}
